    // grunt.registerTask("persistVersion", function () {
    //     console.log("Persisting Versions...");

    //     // smallstack version
    //     var versionCheckFile = "app/packages/smallstack-core/package.js";
    //     if (!grunt.file.exists(versionCheckFile)) {
    //         throw new Error("Version cannot be persisted since file does not exist : " + versionCheckFile);
    //     }

    //     var versionCheckFileContent = grunt.file.read(versionCheckFile);
    //     var regex = /([\'|\"]?version[\'|\"]?[ ]*:[ ]*[\'|\"]?)(\d+\.\d+\.\d+-?[a-zA-Z]*)([\'|\"]?)/;
    //     var matches = regex.exec(versionCheckFileContent);
    //     var version = matches[2];
    //     if (version === null || version === undefined)
    //         throw new Error("Could not find version in file : ", versionCheckFile);
            
    //     // project version
    //     var packageJson = grunt.file.readJSON('package.json');

    //     var content = "";
    //     content += "// THIS FILE IS AUTO-GENERATED BY 'grunt compile'!\n\n";
    //     content += "declare var versions: { smallstack: string, project: string, compileDate: number };\n\n";
    //     content += "versions = {\n";
    //     content += "\tsmallstack: \"" + version + "\",\n";
    //     content += "\tproject: \"" + packageJson.version + "\",\n";
    //     content += "\tcompileDate: " + new Date().getTime() + "\n";
    //     content += "}";

    //     grunt.file.write("app/shared/versions.ts", content);
    // });